Q&A
===
:date: 12/02/2017
:revision: 0.1
:experimental:

== Course Logistics Q&A

== Technical Q&A
=== Testing
- Question: Can Wiremock be used with Spock testing framework?
	* Answers:
	** See here, looks like a clean approach to use Wiremock capabilities with Spock, but without 
	DSL static import baggage: https://github.com/tomjankes/wiremock-groovy

- Question: Can Spring Cloud Contract Consumer Annotations be Support at Test Class method level
versus Class Level?

- Question: Can Spring Cloud Contract Consumer Annotations support tagging multiple versions, or
version increments?

- Eureka Standalone (not running on CF) Questions: 
	* How to configfure Eureka Zone Declarations in Standalone (IaaS, Virtualized) with scalable 
	and multi-zone deployment
	* Significance/Configuration of Eureka Hostname?  How should be configured?

- How do the Spring Cloud Config Clients know how to look up the Config Service endpoints when
Discovery is enabled?
	* Answer:  By default the Config client will look for "configserver" application URLs from
	Service Registry.  But if desired to name config server differently, may be configured through spring.cloud.config.discovery.serviceId property.  See: http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.4.0.RELEASE/single/spring-cloud-config.html#discovery-first-bootstrap

- How to use Git Labels with Config Server?
	* Answer: The general idea is to configure label for application in an environment.  This is done at the Config Server configuration, and the combination of Spring Application Name and Profile driven from application config will point to a Git backend profile.  The appropriate Git backend profile will have the label in the path, or the label may be parameterized in environment.
	* See more here: http://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.3.1.RELEASE/#_environment_repository[Config Server Environment Repository]
	